### ISSUE TITLE
Sample AWS lambdas based Step function pipeline

### ISSUE THREAD

**Issue by dattachandan** [aws-samples/amazon-textract-idp-cdk-stack-samples#1]
Hi Martin

Is this the code for the demo for the step function shown at re:mars [here](https://youtu.be/D6wU_M4oXg8?t=1923)

**Comment by schadem** [comment]
Yes, essentially same codebase. The re:Mars demo had a slightly earlier version.

**Comment by schadem** [comment]
added the links to the code base to the YouTube video as comment.
